### ISSUE TITLE
MeanOrientationVFE

### ISSUE THREAD

**Issue by andy690** [TRAILab/PDV#10]
I found it in mean_vfe.py, I wonder what it does and how can I use him

**Comment by jskhu** [comment]
This is an artifact of from other experiments and PDV does not use this VFE method. However, to answer your question `MeanOrientationVFE` adds the ground truth bounding box orientation as an additional channel to the voxel feature input (xyz + intensity + elongation + _orientation_). One thing to keep in mind is that `MeanOrientationVFE` uses the ground truth labels during training: https://github.com/TRAILab/PDV/blob/f72f4f191f93d8a8ca301e46ebc69893ef6166e1/pcdet/models/backbones_3d/vfe/mean_vfe.py#L70-L72.

**Comment by andy690** [comment]
Thank you for your reply. Perhaps assisting auxiliary network supervision to help establish the relationship between the orientation of voxels and ground truth can help us improve performance.

**Comment by jskhu** [comment]
Yup, that was one of the early ideas that we explored but didn't end up pursuing for this work.
