### ISSUE TITLE
About the accuracy of PDV on Kitti test sets

### ISSUE THREAD

**Issue by S-Eternal-S** [TRAILab/PDV#13]
Hello, authors.
The ground truth of the kitti test set is not available, how do you calculate the accuracy of the network on the test set?

**Comment by jskhu** [comment]
You can evaluate it on the KITTI online benchmark: https://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d. You can generate the results for the benchmarks by specifying the `--save_to_file` command in `tools/test.py`: https://github.com/TRAILab/PDV/blob/024a3695cae782adf7a5fa12c34b0ad461e0844c/tools/test.py#L42

**Comment by S-Eternal-S** [comment]
Thank you very much!
