### ISSUE TITLE
The referenced results of PVRCNN(++) 

### ISSUE THREAD

**Issue by Abyssaledge** [TRAILab/PDV#2]
Hi,
Nice work!
May I ask where the results of PVRCNN and PVRCNN++ come from? The numbers look a little bit strange to me since I can not find them in the original papers of PVRCNN(++).

**Comment by kts707** [comment]
Hi and thanks for the interest!

The referenced PV-RCNN and PV-RCNN++ results are from Table 13 in their arXiv submission [v1](https://arxiv.org/abs/2102.00463v1) on Jan 31, 2021.

**Comment by jskhu** [comment]
To further clarify, the current PV-RCNN++ results on arXiv were updated after the submission timeline for CVPR 2022.

**Comment by Abyssaledge** [comment]
Got it. Thanks for you replies!
