### ISSUE TITLE
GLEW could not be initialized: Missing GL version

### ISSUE THREAD

**Issue by KyleYueye** [TRAILab/PDV#3]
Hello, i've met a problem in running demo.py
`2022-04-04 14:55:26.887 (  15.100s) [        F0A55E80]vtkOpenGLRenderWindow.c:493    ERR| vtkEGLRenderWindow (0x561980223bb0): GLEW could not be initialized: Missing GL version `
`run-demo.sh: line 19:  7579 Segmentation fault      (core dumped)`
I've tried several approaches but all of them failed. Do you have any idea about this bug?

**Comment by jskhu** [comment]
Haven't seen this issue myself, but maybe this thread can help: https://github.com/openai/mujoco-py/issues/268. I use `mayavi==4.7.2` in my environment.
