### ISSUE TITLE
what is the role of MAX_NUM_BOXES？

### ISSUE THREAD

**Issue by Yzichen** [TRAILab/PDV#6]
Thanks for your work, I would like to know what is the role of MAX_NUM_BOXES, is it because the RoIs may have overlap, causing a point to fall into different RoI?

**Comment by jskhu** [comment]
Yes, that's correct! In the original `points_in_boxes_gpu`, each point is assigned a single box id. We modify the code to allow for each point to be assigned to up to `MAX_NUM_BOXES` boxes for accurate point density estimation.
