### ISSUE TITLE
Pointcloud range and voxel size

### ISSUE THREAD

**Issue by KyleYueye** [TRAILab/PDV#8]
For my custom dataset, the pointcloud range and voxel size are defined by what? How can i calculate these two arguments?

**Comment by jskhu** [comment]
They are defined in your dataset config:

https://github.com/TRAILab/PDV/blob/main/tools/cfgs/dataset_configs/kitti_dataset.yaml#L4
https://github.com/TRAILab/PDV/blob/main/tools/cfgs/dataset_configs/kitti_dataset.yaml#L65

These are based on how large your input point cloud is and the voxel resolution you want.
